services:
    jenkins-docker:
        container_name: jenkins-docker
        image: docker:dind
        privileged: true
        ports:
            - 2376:2376
        networks:
            jenkins:
                aliases:
                    - docker
        env_file:
            - stack.env
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
        command: --storage-driver overlay2
    myjenkins-blueocean:
        container_name: jenkins-blueocean
        depends_on:
            - jenkins-docker
        ports:
            - 8080:8080
            - 50000:50000
        build:
            context: .
        restart: on-failure
        networks:
            - jenkins
        env_file:
            - stack.env
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
networks:
    jenkins:
        external: true
        name: jenkins
volumes:
    jenkins-docker-certs:
        external: true
        name: jenkins-docker-certs
    jenkins-data:
        external: true
        name: jenkins-data
