services:
  caddy:
    container_name: caddy
    build:
        context: ./
    restart: unless-stopped
    networks:
        - caddy_proxy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    env_file:
      -  stack.env
    volumes:
      - ${MAIN_DIR}/conf:/etc/caddy
      - ${MAIN_DIR}/site:/srv
      - caddy_data:/data
      - caddy_config:/config
networks:
    caddy_proxy:
        name: caddy_proxy
volumes:
  caddy_data:
      name: caddy_data
  caddy_config:
      name: caddy_config
